[target.x86_64-pc-windows-msvc]
linker = "C:\\Program Files\\Microsoft Visual Studio\\2026\\VC\\Tools\\MSVC\\14.50.35717\\bin\\Hostx86\\x64\\link.exe"

[env]
CC = "C:\\Program Files\\Microsoft Visual Studio\\2026\\VC\\Tools\\MSVC\\14.50.35717\\bin\\Hostx86\\x64\\cl.exe"
CXX = "C:\\Program Files\\Microsoft Visual Studio\\2026\\VC\\Tools\\MSVC\\14.50.35717\\bin\\Hostx86\\x64\\cl.exe"
INCLUDE = "C:\\Program Files\\Microsoft Visual Studio\\2026\\VC\\Tools\\MSVC\\14.50.35717\\include;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\um;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.26100.0\\shared"
LIB = "C:\\Program Files\\Microsoft Visual Studio\\2026\\VC\\Tools\\MSVC\\14.50.35717\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64"
